### ISSUE TITLE
When user cancals the SDK download, we should remove the folder and its contents

### ISSUE THREAD

**Issue by sarahcodes100** [DeerajTheepshi/processing-android#21]
Currently, if you cancel, the folder and its current downloads remain on disk. We should remove them so the PDE doesn't erroneously think the complete SDk has been installed

**Comment by DeerajTheepshi** [comment]
Yeah. This is needed. 
- When user cancels SDK download we can remove the SDK folder.
- We can however keep the temp folder so that we can solve : https://github.com/processing/processing-android/issues/537

Solved using: d7d6fc4bf1db197e7da74b317a718bc6d9c2d991

Close if you feel the commit is fine. @sarahlensing
